# docker-compose.yml
# Se ha eliminado la línea 'version' por ser obsoleta

services:
  db:
    image: mariadb:10.5
    container_name: mariadb_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - app-network

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - ./backups:/var/www/html/data/admin/files/Backups
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
    depends_on:
      - db
    networks:
      - app-network

  backup-runner:
    build: ./backup
    container_name: backup_runner_instance
    restart: "no"
    volumes:
      # Montamos las credenciales de AWS (solo lectura)
      - ~/.aws:/root/.aws:ro
      - ./my-public-key.asc:/app/my-public-key.asc:ro
      # Montamos el directorio de backups
      - ./backups:/backups
    environment:
      - GPG_RECIPIENT=${GPG_RECIPIENT}
      - S3_BUCKET=${S3_BUCKET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
      - nextcloud
    networks:
      - app-network

volumes:
  db_data:
  nextcloud_data:

networks:
  app-network:
    driver: bridge
