version: "3.8"

# Definición de los servicios (contenedores)
services:
  # Servicio de la Base de Datos
  db:
    image: mariadb:10.5 # Usamos una imagen oficial de MariaDB
    container_name: mariadb_db
    restart: always # Siempre reiniciar el contenedor si se detiene
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql # Monta un volumen para persistir los datos de la BD
    environment:
      # Carga las variables desde el archivo .env
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - app-network

  # Servicio de Nextcloud
  nextcloud:
    image: nextcloud:latest # Usamos la imagen oficial de Nextcloud
    container_name: nextcloud_app
    restart: always
    ports:
      - "8080:80" # Mapea el puerto 8080 del host al 80 del contenedor
    volumes:
      # Monta un volumen para los datos de Nextcloud
      - nextcloud_data:/var/www/html
      # Montamos un directorio local para que el script de backup pueda dejar los archivos
      - ./backups:/var/www/html/data/admin/files/Backups
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db # Apunta al servicio 'db'
    depends_on:
      - db # Indica que este servicio depende de la base de datos
    networks:
      - app-network

  # Servicio que ejecuta nuestro script de respaldo
  backup-runner:
    # Construye la imagen desde el directorio 'backup'
    build: ./backup
    container_name: backup_runner_instance
    # No reiniciar, es una tarea que se ejecuta y termina
    restart: "no"
    volumes:
      # Montamos las credenciales de AWS (solo lectura)
      - ~/.aws:/root/.aws:ro
      # Montamos las llaves GPG
      - ~/.gnupg:/root/.gnupg
      # Montamos el mismo directorio de backups que Nextcloud para que el script pueda escribir en él
      - ./backups:/backups
    environment:
      # Pasamos las variables de entorno necesarias para el script
      - GPG_RECIPIENT=${GPG_RECIPIENT}
      - S3_BUCKET=${S3_BUCKET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
      - nextcloud
    networks:
      - app-network

# Definición de volúmenes para persistencia de datos
volumes:
  db_data:
  nextcloud_data:

# Definición de la red para que los contenedores se comuniquen
networks:
  app-network:
    driver: bridge
